version: "3"
services:
  selenium:
    image: seleniarm/standalone-chromium:4.1.1-alpha-20220119
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
  app:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
